FirstAspNetCore2MVC/Controllers/FeedBackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FirstAspNetCore2MVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FirstAspNetCore2MVC.Controllers
{
    [Authorize]
    public class FeedBackController : Controller
    {
        private IFeedBackRepository repository;
        public FeedBackController(IFeedBackRepository repository)
        {
            this.repository = repository;
        }

        // GET
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(FeedBack feedBack)
        {
            // Model binding happens before Index method is invoked, Model validation the same
            // when model binding happens, a Site property ModelState is created, which contains
            // the error encountered
            if (ModelState.IsValid)
            {
                repository.AddFeedBack(feedBack);
                return RedirectToAction("FeedBackDone");
            }
            // asp-validation-summary or <span asp-validation-for> in html will show the errors
            return View(feedBack);
        }

        // GET
        public IActionResult FeedBackDone()
        {
            return View();
        }
    }
}

FirstAspNetCore2MVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>
@inject SignInManager<IdentityUser> SignInManager
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Jun's First ASP Net core mvc</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
<div>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index" class="navbar-brand">Junguoguo's Pie Shop</a></li>
                    <li><a asp-controller="FeedBack" asp-action="Index" class="navbar-brand">Give me FeedBack</a></li>
                </ul>
                @if (SignInManager.IsSignedIn(User))
                {
                    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
                          method="post" class="navbar-right">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
                        </ul>
                    </form>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li><a id="registerLink" asp-controller="Account" asp-action="Register">Register</a></li>
                        <li><a id="loginLink" asp-controller="Account" asp-action="Login">Log in</a></li>
                    </ul>
                }
            </div>
        </div>
    </nav>
        <div class="container body-content">
            <div class="row">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>